export const units = [
  { t: 'g' },
  { t: 'kg' },
  { t: 'ml' },
  { t: 'l' },
  { t: 'pc' },
  { t: 'pk' },
  { t: 'gl' },
  { t: 'tbsp' },
  { t: 'tsp' },
  { t: 'c' },
  { t: 'qt' },
  { t: 'gal' },
  { t: 'oz' },
  { t: 'lb' },
  { t: 'pc' },
  { t: 'pk' },
  { t: 'sl' },
];
